# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Pablo Pascual Cobo"
email: pablopascualcobo@gmail.com
description: "Pablo Pascual Cobo is a postdoctoral researcher at ISTA working on information theory, coding, and high-dimensional statistics."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pablopasc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: PabloPasc
linkedin_username: pablo-pascual-cobo-022abb174
scholar_userid: 5XcF5JUAAAAJ
og_image: "/pablo_photo.jpg"
author:
  name: "Pablo Pascual Cobo"
  avatar: "/pablo_photo.jpg"
  bio: "Postdoctoral Researcher at ISTA"
  location: "Klosterneuburg, Austria"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:pablopascualcobo@gmail.com"
    - label: "LinkedIn Profile"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/pablo-pascual-cobo-022abb174/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=5XcF5JUAAAAJ"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/PabloPasc"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-sitemap

minimal_mistakes_skin: "default"
locale: "en-US"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
